version: '3.9'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=messaging_db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=message123
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: messaging_db
      MYSQL_DB: messaging_db      
      MYSQL_USER: messaging_user
      MYSQL_PASSWORD: messaging_pass
      MYSQL_ROOT_PASSWORD: Pogbance12
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
