# Generated by Django 4.2.21 on 2025-06-13 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_message_edited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='edited',
            new_name='edited_by',
        ),
        migrations.AddField(
            model_name='message',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='messaging.message'),
        ),
    ]
